from .config import OUTLOOK_EMAIL, OUTLOOK_PASSWORD, CRITICAL_HOSTS, RECIPIENTS_EMAILS, EXCLUDE_GROUPS, REDIS_HOST, EMAIL_TAC, TELEGRAM_TOKEN
from .logger import setup_logger


__all__ = [
    'OUTLOOK_EMAIL',
    'OUTLOOK_PASSWORD',
    'CRITICAL_HOSTS',
    'RECIPIENTS_EMAILS',
    'EXCLUDE_GROUPS',
    'REDIS_URL',
    'EMAIL_TAC',
    'TELEGRAM_TOKEN',
    'setup_logger'
]
